/**
 * Centralized locators and constants for ask.permission.ai.
 * 
 * Locators prioritize resilient data-testid attributes exposed by the application
 * rather than fragile, autogenerated styling classes. Chat message bubbles use
 * structural alignment classes (justify-start for agent responses).
 */

export const SELECTORS = {
  // Input and Interactive Controls
  INPUT: '[data-testid="agent-chat-input"]',
  SEND_BUTTON: '[data-testid="agent-chat-input-send-button"]',
  STOP_BUTTON: '[data-testid="agent-chat-input-stop-button"]',

  // Authentication Entry Points
  LOGIN_BUTTON: '[data-testid="log-in-button"]',
  SIGNUP_BUTTON: '[data-testid="sign-up-button"]',

  // Chat Interface Structure
  AGENT_MESSAGE: 'div.flex.justify-start',
  AGENT_MESSAGE_TEXT: 'div.flex.justify-start div.text-md',

  // Branding / Headers
  PAGE_TITLE: '[data-testid="ai-page-title"]',
  PAGE_DESCRIPTION: '[data-testid="ai-page-description"]',

  // OneTrust Banner
  COOKIE_REJECT_BUTTON: '#onetrust-reject-all-handler, button:has-text("Reject All")',
} as const;

export const SUGGESTED_TOPICS = [
  'What is Permission',
  'Best way to earn ASK',
  'How permission uses my data',
  'What is passive earning',
  'What is data ownership',
  'Permission Wallet',
] as const;

/**
 * Markers emitted in the UI when the underlying AI agent API fails (e.g. 500 internal error).
 * Valid non-deterministic responses must never match these markers.
 */
export const ERROR_MARKERS = [
  'i ran into an issue',
  'something went wrong',
  'please try again',
  'error occurred',
] as const;
